debug: true
db-file: scan.db
rtlfm: rtl_fm
frequency: 152.00750M
multimon: multimon-ng
ppm: 0
output-channels:
  test:
    plugin: "stdout"
    option: ""
    channel: "X"
  ABC:
    plugin: "stdout"
    option: ""
    channel: "Y"
  something:
    plugin: "stdout"
    option: ""
    channel: "ABCDEF"
channel-mappings:
  0630777: 
   - ABC
  0620777:
   - something
